site_name: Invoice-AR
site_url: http://www.indoguna.co.id/
site_description : CNW-INV_AR
site_author : IT R&D
copyright : Copyright &copy; 2023 Indoguna Group, Maintained by @IT
 
nav:
    - index.md
    - Master Data : mastercustomer.md  
    - Penagihan : penjualan.md  
theme : 
    name : material
    logo : asset/logocnw1.png
    favicon : asset/logocnw2.png
    palette:
        scheme: default
        primary: teal
extra_css:
    - css/extra.css
    - css/pdf-print.css
markdown_extensions:
    - toc:
        permalink: 
    - attr_list
    - def_list
    - tables
    - pymdownx.highlight:
        use_pygments: false
    - pymdownx.snippets
    - pymdownx.superfences  

plugins:
    - search    
    - mermaid2 
    - pdf-export:
        combined: false
        media_type: print
    - with-pdf: 
        cover_subtitle: Pedoman Penggunaan
        output_path: "../docs.pdf"